### PR TITLE
Show activate button if app has been disabled

### LINKED ISSUE #262: Hide/disable "Open" button when app is disabled

### PR DESCRIPTION
**Pull request by Hanouta**
This replaces the "Open" button with an "Activate" button if the app has been disabled.
Tapping on the button will open the AppInfo page for the corresponding app in the system settings.

Closes: #262

### CODE REVIEW

**Comment by matchboxbananasynergy** [comment]
I think it might be best for the option to be labeled "enable", and not "activate". It's best to stick with the terminology that Android uses.

Also, I noticed there's another option labeled "Couldn't open AppInfo". When would that be the case? Settings app crashing or something else I'm missing? Either way, something about the wording of that that I don't particularly like.

**Comment by Hanouta** [comment]
You're right, it should be the same terminology, I just assumed its "activate" in English because in German its "aktivieren".

The "Couldn't open AppInfo" would happen if "package:app-id" can't be resolved, aka the app isn't installed anymore. In practice it shouldn't be able to trigger that code path after uninstalling the app, because the "Enable" button gets replaced with an "Install" button, but just to be sure I guess.

**Comment by Hanouta** [comment]
Changed the wording to "Enable"

**Review by lberrymage — CHANGES_REQUESTED** [review]
Thanks! I like this, but there's one issue with it: the package status isn't updated immediately whenever the app is enabled or disabled. Instead, the Accrescent activity has to be force-closed and opened again for the "Enable" button to appear after disabling (or the "Open" button after enabling).

It seems like all that's needed is to listen for [`ACTION_PACKAGE_CHANGED`](https://developer.android.com/reference/android/content/Intent#ACTION_PACKAGE_CHANGED) in `AppStatusChangeBroadcastReceiver.kt`, but some brief testing on my end shows more work is required.

**Comment by Hanouta** [comment]
> Thanks! I like this, but there's one issue with it: the package status isn't updated immediately whenever the app is enabled or disabled. Instead, the Accrescent activity has to be force-closed and opened again for the "Enable" button to appear after disabling (or the "Open" button after enabling).
> 
> It seems like all that's needed is to listen for [`ACTION_PACKAGE_CHANGED`](https://developer.android.com/reference/android/content/Intent#ACTION_PACKAGE_CHANGED) in `AppStatusChangeBroadcastReceiver.kt`, but some brief testing on my end shows more work is required.

I just added ACTION_PACKAGE_CHANGED to the listener and it seems to work just fine here, what issues did you encounter?
(Tested using split screen between Accrescent and the settings app on GOS and it updated immediately)

**Comment by lberrymage** [comment]
Ah, I was being silly and forgot to add the action to the broadcast receiver registration call. I only listened for it in the broadcast receiver.

**Review by lberrymage — APPROVED** [review]

**Comment by lberrymage** [comment]
Thanks!

**Pull request merged**
