### PR TITLE
Add app screenshots to the README

### LINKED ISSUE #214: Add screenshots
As a potential user i cannot see which app i'm downloading, please add screenshots to the readme👀

### PR DESCRIPTION
**Pull request by meenbeese**
Closes #214 by adding several screenshots of the app and displaying them in a table in the README.

### CODE REVIEW

**Comment by lberrymage** [comment]
Hi, and thank you! A few quick questions:

- Out of curiousity, where does the folder structure come from?
- What tool did you use to generate these screenshots?
- Would you be able to reduce the JPEG quality of these images a bit to save some space in the git repo?

I mostly ask the first two questions so there's some reproducibility when the screenshots are inevitably updated.

**Comment by meenbeese** [comment]
Hi there!

1. This folder structure is mostly used to display the metadata in apps that are on F-Droid. I just set this as a default and this can be changed on demand given that Accrescent won't be on F-Droid for obvious reasons.
2. I took the screenshots on my personal Android device and then cropped them using GIMP. It is not the easiest option perhaps as screenshots can be quickly taken using Android Studio.
3. I could easily reduce their sizes by compressing them online but they only total to a size of around 1 MB combined. I don't know if saving that little space is important at the cost of having worse image quality as JPG is already a compressed format.

Still, I would reduce their size once you let me know if this is something that you value.

**Review by lberrymage — CHANGES_REQUESTED** [review]
My main concern about image size isn't so much about how much storage they consume *now*, but how much storage usage will accumulate in the git repo as the images are updated over time. I think we should instead host the images themselves on Accrescent's web server(s) while linking to them externally in markdown so they're not checked in to git. That way we can update them frequently without bloating the git history size.

I've copied the images to the following URLs:

- https://accrescent.app/meta/screenshots/home.jpeg
- https://accrescent.app/meta/screenshots/app-details.jpeg
- https://accrescent.app/meta/screenshots/settings.jpeg
- https://accrescent.app/meta/screenshots/settings-material-you.jpeg

Could you update the image links to these remote URLs?

**Comment by meenbeese** [comment]
I also think this approach makes more sense. I implemented the requested changes.

**Review by lberrymage — APPROVED** [review]
Sweet, thank you!

**Pull request merged**
