### PR TITLE
Add option to prompt user for installs when privileged

### PR DESCRIPTION
**Pull request by lberrymage**
When Accrescent is privileged, the OS doesn't prompt the user when installing an app. This may be undesirable since the user could accidentally press "Install" on unwanted apps. This commit allows the user to force OS prompts for installations when Accrescent is privileged. Note this doesn't affect app updates i.e. pressing an "Update" button while the option is enabled will not prompt the user.

The option is disabled by default.

### CODE REVIEW

**Comment by lberrymage** [comment]
To test before merging:

- [x] Verify that toggle is disabled by default when Accrescent is privileged
- [x] Verify that installing new apps requires user action when toggle is enabled and Accrescent is privileged
- [x] Verify that updating existing apps does not require user action when toggle is enabled regardless of whether Accrescent is privileged

**Comment by PatrykMis** [comment]
Privileged - you mean it's put in `/system/priv-app`?

**Comment by lberrymage** [comment]
Yes, for `INSTALL_PACKAGES` and `DELETE_PACKAGES`.

**Comment by PatrykMis** [comment]
Finally, I've build the app, created Magisk module which installs Accrescent as the system priv-app with privileged permissions to be able to test this PR.

1. Toggle is enabled by default when Accrescent is privileged. I've tripple-checked that by reinstalling and clearing cash and data.
2. Installing new apps requires user action when toggle is enabled and Accrescent is privileged. Obviously it installs apps without prompt when the switch is disabled.
3. Not able to test for obvious reason.

Although app is priviliged, it still needs install unknown packages permission to be granted manually.

**Comment by PatrykMis** [comment]
Forgot to add that whether the switch is enabled or disabled, Accrescent uninstalls apps always silently without any prompt or notification. This could be more dangerous than installing app without confirmation.

**Comment by lberrymage** [comment]
@PatrykMis First of all, thank you for taking the time and effort to test this.

> 1. Toggle is enabled by default when Accrescent is privileged. I've tripple-checked that by reinstalling and clearing cash and data.

I looked over my PR again and I see the issue. When I have time, I'll rebase and fix it.

> 2. Installing new apps requires user action when toggle is enabled and Accrescent is privileged. Obviously it installs apps without prompt when the switch is disabled.

Great!

> 3. Not able to test for obvious reason.

Once everything else works, I can bump the version of the testing KeePassDX build so you can test updates.

> Although app is priviliged, it still needs install unknown packages permission to be granted manually.

Are you asked to grant it, and do you need to grant it for Accrescent to work? If so, under what circumstances (installing/uninstalling and toggle enabled/disabled)?

**Comment by lberrymage** [comment]
> Forgot to add that whether the switch is enabled or disabled, Accrescent uninstalls apps always silently without any prompt or notification. This could be more dangerous than installing app without confirmation.

I forgot about this when I initially made the PR, but I agree. Unfortunately, there isn't an equivalent API for making the OS ask for confirmation when uninstalling packages, so I think we'll need to add our own custom confirmation prompt.

**Comment by PatrykMis** [comment]
> Are you asked to grant it, and do you need to grant it for Accrescent to work? If so, under what circumstances (installing/uninstalling and toggle enabled/disabled)?

It asks for allowing unknown sources after download and before installation, only when toggle is enabled. I can uninstall without it granted regardless of the switch.

I'm afraid that creating custom confirmation prompt will be required for installing too, due to above situation.

**Comment by lberrymage** [comment]
That's... very strange. That behavior seems to imply that when `USER_ACTION_REQUIRED` is passed, the OS isn't recognizing the app as having `INSTALL_PACKAGES`. Initially feels like an AOSP bug, but perhaps that's just how they chose to implement it.

Regardless, I don't think this is a significant issue since it can be assumed that if Accrescent is built into the OS as a priv-app, it can be granted `REQUEST_INSTALL_PACKAGES` by the OS by default. It feels a *little* hacky since the user can deny `REQUEST_INSTALL_PACKAGES`, but if it can be granted by default by the OS I don't think it's really an issue. My only other concern is that using the OS dialog for installation and a custom dialog for uninstallation is inconsistent, but that's an implementation detail that can be changed later, so I'm not concerned about it for this PR.

**Comment by lberrymage** [comment]
> I looked over my PR again and I see the issue. When I have time, I'll rebase and fix it.

@PatrykMis The toggle should now by disabled by default in privileged mode.

**Comment by PatrykMis** [comment]
> The toggle should now by disabled by default in privileged mode.

Unfortunately, it's still enabled by default.

**Comment by lberrymage** [comment]
Round 2. Should *actually* be fixed now.

**Comment by PatrykMis** [comment]
Yes, everything works as expected.

**Comment by lberrymage** [comment]
Great. I'll go ahead and add a confirmation dialog for uninstalls, then we can test it along with updates and call it good for merging.

> My only other concern is that using the OS dialog for installation and a custom dialog for uninstallation is inconsistent, but that's an implementation detail that can be changed later, so I'm not concerned about it for this PR.

I've thought about this behavior more and I think there's another (better) reason to use a custom dialog for installation. If the OS is requiring `REQUEST_INSTALL_PACKAGES` with the option enabled, it's most likely considering apps as installed from a third-party source, meaning UserManager restrictions could block installations even when Accrescent is privileged.

I'm still not concerned about it for this PR, but it might be worth filing an issue with AOSP if that's the case because it doesn't really make sense.

**Comment by lberrymage** [comment]
Added the uninstall confirmation dialog. Shouldn't need much testing. Note it's not tied to the toggle and is instead always enabled in privileged mode by design.

**Comment by PatrykMis** [comment]
Great. Dialogue is shown, buttons are working as expected, switch is off by default, everything ok.

**Comment by PatrykMis** [comment]
Just one note: Uninstall button for Accrescent when it is privileged doesn't make sense as it simply cannot be uninstalled.

**Comment by lberrymage** [comment]
> Great. Dialogue is shown, buttons are working as expected, switch is off by default, everything ok.

Cool. All that's left is testing updates then (which I'm 99% sure will work). I can upload an update to KeePassDX whenever.

> Just one note: Uninstall button for Accrescent when it is privileged doesn't make sense as it simply cannot be uninstalled.

Thanks! I didn't think of that. I'll address it after this is merged.

**Comment by PatrykMis** [comment]
I can test it today and tomorrow. Are you going to notify when you bump version or you want to do it silently and check if the app updated it automatically without any issues?

**Comment by lberrymage** [comment]
I'll let you know when I bump the version. I'm sure enough that automatic updates will be fine, but the UI code around manual updates is a bit more complicated so I mainly want to test that.

**Comment by PatrykMis** [comment]
The update was completed without problems, although I had to trigger it manually ("updates" tab then press the button). There's another issue with TalkBack which doesn't read any label for update button and open button but I'll make eventually another PR.

**Comment by lberrymage** [comment]
Sweet! Thank you so much for testing this.

**Pull request merged**
