### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by PatrykMis**

### CODE REVIEW

**Comment by BHydden** [comment]
Pretty sure he has a bot that does this periodically.

**Comment by PatrykMis** [comment]
Not doing any updates without testing, and if you think (wrongly, of course) I have a bot for doing this, do it better. Not sure why I would have to do this...

**Comment by BHydden** [comment]
I think you have misunderstood me. I meant the dev of this project uses dependabot to keep dependencies updated, so users don't need to put up PRs for it, as you have done here. I wasn't intending to say you were using a bot.

**Comment by PatrykMis** [comment]
Ah ok, sorry @BHydden  for misunderstanding.

**Comment by BHydden** [comment]
All good, I should try harder not to use unclear language 👍

**Comment by lberrymage** [comment]
Thanks!

**Pull request merged**
